### ISSUE TITLE
Is it possbile to performe ocr task using RNNSharp ?

### ISSUE THREAD

**Issue by BackT0TheFuture** [zhongkaifu/RNNSharp#1]
Hi there,

recently I wanna do some tests about sequence labelling(OCR without segment) via RNN

I googled and found this project , Thanks for your efforts 

I have hundreds of handwritten word images and the corresponding word

Would you like to give me some instruction about this problem

any advice will be welcomeed. thanks in advance !

Best regards,

**Comment by zhongkaifu** [comment]
Yes. RNN has good performance on OCR task, such as hand writing recognition. Generally, you need to segment handwritten word images at first, and then recognize each word in the image.

The feature selection is the key important part. You can design and combine your feature manually, and RNN can also help you to generate features automatically, such as embedding input pixels into vectors. 

With reasonable feature set, you can choose a classifier to detect which word is in the image.

**Comment by BackT0TheFuture** [comment]
I'm a newbie on Machine Learning but very interested in it.
do you mean the segmentation is needed before ocr using RNN ?
I'm not good at c#, is there some document for RnnSharp ?
would you like to make a little ocr task demo using RNNSHARP when you are free?
Thanks !

Best regards,
