### ISSUE TITLE
Example file

### ISSUE THREAD

**Issue by LiangYuzhi** [zhongkaifu/RNNSharp#10]
Is there any runnable example? I've change the code a little bit and tried to run it, but the error rate is unreasonable high

**Comment by zhongkaifu** [comment]
You can download demo package from release section. It contains runnable examples.

What's command line did you run ? What's change did you make ? And what's the error rate before your changes ?

**Comment by LiangYuzhi** [comment]
Thank you for your timely reply:)

The description of the demo package is 'To get the demo package, please access [DOWNLOADS] page and download the package', what is the download link?

Basically, I have a set of character embedding generated by word2vec, and let it as input of RNNSharp to do some Chinese segment task. It's similar to the task in this paper: http://arxiv.org/pdf/1404.4714.pdf

I've change the code as taking a matrix as input (though this is not necessary for this task, but I have following tasks has to take matrix rather than load word embedding as input). By setting breakpoint, I can see the data is loaded properly:
![image](https://cloud.githubusercontent.com/assets/17334812/13659059/4c5e98d6-e6b8-11e5-95df-6eda24bdd70b.png)

I used 4 tags 'S/B/M/E' as output, But the segmentation result is always BEBEBESBE/BEBEBEBE. 

For training, I used
-layersize 50 
-crf 1

**Comment by bratao** [comment]
LiangYuzhi, could you try without a crf?

Here, I couldn't find a input that crf works. I have the impression that or
it is not working well, or it expect an specific input that I haven't
figured out.

**Comment by zhongkaifu** [comment]
@LiangYuzhi  Sorry that I didn't update readme file in time, you can get demo package from "release" section. It contains some demo as your example.

Which modeltype did you use ? SimpleRNN or LSTM ?
Which your entire command line ? Could you please show some information from log ?

**Comment by bzaar** [comment]
@zhongkaifu I couldn't find a "release" section in this repository. +1 for adding an example file.

**Comment by zhongkaifu** [comment]
Hi bzaar,
You could get demo and example there: https://github.com/zhongkaifu/RNNSharp/releases

**Comment by LiangYuzhi** [comment]
The error rate problem might be caused by my training set, this issue can be closed. Thanks
