### ISSUE TITLE
Possible combinations of various RNNs types

### ISSUE THREAD

**Issue by My-Khan** [zhongkaifu/RNNSharp#17]
Hello,
i am little bit confused about the various combinations of model types and possible direction e.g forward and bidirectional. i am new to RNN architecture so please guide urgently. 
is the following combinations are valid ? if not then please explain little bit. thanks in advance.
With Single Hidden Layer e.g –layersize 200
Bi-Directional LSTM-RNN without CRF
Bi-Directional LSTM-RNN with CRF
Bi-Directional BPTT-RNN without CRF
Bi-Directional BPTT-RNN with CRF
Forward LSTM-RNN without CRF
Forward LSTM-RNN with CRF
Forward BPTT-RNN without CRF
Forward BPTT-RNN with CRF
With Two  Hidden Layer (deep layers) e.g –layersize 200,100
Bi-Directional LSTM-RNN without CRF
Bi-Directional LSTM-RNN with CRF
Bi-Directional BPTT-RNN without CRF
Bi-Directional BPTT-RNN with CRF
Forward LSTM-RNN without CRF
Forward LSTM-RNN with CRF
Forward BPTT-RNN without CRF
Forward BPTT-RNN with CRF

**Comment by zhongkaifu** [comment]
Yes, they are valid. You could set different parameter values to train them.

**Comment by My-Khan** [comment]
Got it, many Thanks
