### ISSUE TITLE
GPU Training

### ISSUE THREAD

**Issue by alexrisman** [zhongkaifu/RNNSharp#2]
Hi, does this library support training on GPU?

**Comment by zhongkaifu** [comment]
Currently, RNNSharp doesn't support training on GPU, but I do have a plan for that. :)

**Comment by BackT0TheFuture** [comment]
Great to hear that. There's one project named "CUDAFY.NET", it allows easy development of high performance CUDA applications in C#.  (CUDAFY.NET)[http://cudafy.codeplex.com/] <_>

**Comment by zhongkaifu** [comment]
Thanks for pointing out. I will look at CUDAFY.NET to see if we can use it.
