### ISSUE TITLE
Supported Features

### ISSUE THREAD

**Issue by My-Khan** [zhongkaifu/RNNSharp#21]
Hello
Hope that you will be fine.
Can you briefly explain impact of each feature type specially the embedding feature and runtime feature on the final results of RNN compared to the traditional CRF which use only one feature type e.g. the template feature.
thanks in advance

**Comment by zhongkaifu** [comment]
Template feature is sparse feature. If current token hits some features, only these features values become non-zero, however, other features values are zero.
Embedding feature is dense feature. each token can point to a vector and the value of this vector will be used as embedding feature.
Runtime feature uses the output of previous tokens as features for current token.

**Comment by My-Khan** [comment]
Many thanks for details.
