### ISSUE TITLE
Model structure

### ISSUE THREAD

**Issue by My-Khan** [zhongkaifu/RNNSharp#22]
Hello ,
Can i represent DRNN in the below structure for Named entity task. any suggestion for improvement will be highly appreciated. Also is it based on Elman Architecture which is described in (Kaisheng Yao et al.,2013) ?
![image](https://cloud.githubusercontent.com/assets/17508897/15565894/4f959d54-2337-11e6-9f5e-1b6c5b25c4ae.png)

**Comment by zhongkaifu** [comment]
Yes. This is a basic RNN model structure: single recurrent hidden layer and forward model. It can be used for NER task. For more complicated model, you could try bi-directional model, deep recurrent hidden layer, different recurrent hidden type(BPTT, LSTM), CRF output and so on.

**Comment by My-Khan** [comment]
many thanks for clarification.
also on the home page of RNNShrap the model structure given their for deep bi-directional RNN-CRF network all the three hidden layer are labeled Hidden layer #1, Hidden layer #1 ,Hidden layer #1  . is this the typing mistake? or its real.

also the equation used from computation is this one 
h(t)=σ(U.x(t)+W.h(t-1) ),             t=1….T    and 
y(t)=g(Vh(t))       

if yes 
then please explain     g(Vh(t)).        

is same equation is used for computation in basic RNN and DEEP RNN?

**Comment by zhongkaifu** [comment]
Thanks for pointing out. It's a typo. They should be "Hidden layer #1", "Hidden layer #2", "Hidden layer #3". I will fix it.

g(Vh(t)) is the function to calcuate y(t) by using the output of hidden layer and weights between hidden layer and y.

**Comment by My-Khan** [comment]
Many thanks. 
can i use your diagrams in my paper with reference?

**Comment by zhongkaifu** [comment]
Sure. I'm glad these diagrams is helpful for your paper.

**Comment by My-Khan** [comment]
so nice of you

**Comment by zhongkaifu** [comment]
Fixed it. Thanks for your pointing it out.

**Comment by My-Khan** [comment]
Appreciated , Is in future there is chance of implementation of Skip-Chain CRF in C# from you?

**Comment by zhongkaifu** [comment]
Maybe, but currently, I have no plan about it.

**Comment by My-Khan** [comment]
Ok thanks for kind reponse
