### ISSUE TITLE
OutofMemoryException

### ISSUE THREAD

**Issue by Bilgeyar** [zhongkaifu/RNNSharp#23]
Thanks for this greet job!
I have got a problem when i start to use the new version( I used the old version on codeplex before)
it throws outofmemory exception when I used old version text2vec tool generated vector.bin file.if there are a way to convert it to new version.

WordEMWrapFeaturizer funcion
model.LoadBinaryModel(filename);
i found that there is no 
 bw.Write(0);//no VQ 
 in the old version,maybe this rises the exception,is there any solutions for this,I donot want to retrain the word_vector.bin.

**Comment by zhongkaifu** [comment]
Yes, model format was changed for VQ which can reduce model size significantly, so Txt2Vec model is not compatible with the previous one.
To avoid retraining word_vector.bin, you could revert Txt2Vec model load code (model.LoadBinaryModl(...)), and still use the previous version without VQ. And then compile RNNSharp by using modified Txt2Vec.dll, then it should work.
