### ISSUE TITLE
Older version?

### ISSUE THREAD

**Issue by lbarwick** [zhongkaifu/RNNSharp#25]
Hi,

Do you have a version available for VS2010 and .NET 4.0?

**Comment by zhongkaifu** [comment]
Sorry that RNNSharp doesn't support .NET 4.0, since some features, such as SIMD, are not available in the version lower than .NET 4.6.

If you want to use RNNSharp on .NET 4.0, you need to remove those features required higher .NET version, or re-implement them by your owned code.

**Comment by lbarwick** [comment]
I there a particular ".cs" that I could change for just LSTM? Or is the project all inter-linked?

Lawrence
Date: Thu, 14 Jul 2016 06:31:25 -0700

**Comment by zhongkaifu** [comment]
You need to change all files if necessary, otherwise, build will fail. If you really want to use it in .NET 4.0, there are two things you need to update:
#1. Update "Parallel.For" to "for" statement and "Parallel.Foreach" to "foreach"
#2. Replace SIMD code with "for/foreach"

Both of above two things are related to encode/decode speeding up.

**Comment by lbarwick** [comment]
Hi,

Have you ever tried to apply LSTM to stock prediction?

I am looking into this, but am wondering how to Sequence the input data.

The basic data element I have is the stock price. SO I have created an array of log(Stock Price changes) which I call "Returns".

Do you think I should feed the LSTM with Input of "Last Return" and target output of "Next Return". i.e a single input value and a single target:

Returns = { 0.1, 0.2, -0.1, 0.5, -0.2 ... }
Samples = { {Input,TargetOupt}...}
Samples = { {{0.1}, 0.2}, {{0.2},-0.1},{{-0.1},0.5}...}

Or provide a longer sequence in the input:
Samples = { { {0.1, 0.2, -0.1}, 0.5},{{0.2, -0.1, 0.5},-0.2}}

Any thoughts greatly appreciated,

Lawrence
Date: Thu, 14 Jul 2016 06:31:25 -0700

**Comment by zhongkaifu** [comment]
I don't think it's good for stock price prediction, but you could try to predict behaviors, such as "Buy", "Hold" and "Sell".
