### ISSUE TITLE
Impact of run-time feature

### ISSUE THREAD

**Issue by My-Khan** [zhongkaifu/RNNSharp#26]
Hello Sir,
hope you will be fine
Would you please like to let me know the impact of run-time features on results, simply why we use run-time features?

**Comment by zhongkaifu** [comment]
Run-time features means RNNSharp uses the previous token's output (T-1) as feature for current token (T). Currently, this feature is only enabled for forward RNN, but not b-directional RNN.

**Comment by My-Khan** [comment]
Many thanks sir, but sir still confused,
Actually whats the logic behind its usage? SIMPLY why run-time features are being considered?

**Comment by zhongkaifu** [comment]
The idea of run-time feature is to provide previous output token as feature to current token. It extends feature we have.

**Comment by My-Khan** [comment]
ok sir got it
