### ISSUE TITLE
LSTM RNN

### ISSUE THREAD

**Issue by Bilgeyar** [zhongkaifu/RNNSharp#27]
when i training a pos tagger using RNN,CRF,RNN+CRF,LSTM+CRF,the result is very good, but LSTM is not better than others,I have same training, development and test corpus, what is my problem?

**Comment by zhongkaifu** [comment]
Thanks @Bilgeyar  for pointing it out. It's a bug when computing output layer in forward pass. I will fix it today. Once's the fixing is checked-in, I will update this thread.

**Comment by zhongkaifu** [comment]
The fixing has already been checked-in. You can check-out the latest source code and compile it.
