### ISSUE TITLE
Plan to Use LSTM for Time Series

### ISSUE THREAD

**Issue by Yandychang1** [zhongkaifu/RNNSharp#28]
I would like to use the LSTM for sequence prediction, I enter a series of numbers, and the network, outputs what number is more likely to come next, with a percent probability. Is this possible with this library? would you have a tutorial/ example  on how could something similar be achieved?

**Comment by zhongkaifu** [comment]
Hi @Yandychang1,

Yes, RNNSharp supports LSTM for sequence prediction. The task you mentioned likes language model task, and RNNSharp definitely support this kind of task.

The latest code already supports it. For tutorial/example,  I'm still working on it, once it's finished, I will release it here. In new demo package, besides existing sequence-label task demos, I will add a new sequence-to-sequence demo task that generating question based on given answers.
