### ISSUE TITLE
Incremental training

### ISSUE THREAD

**Issue by bill3code** [zhongkaifu/RNNSharp#32]
Hello!
You do a great job!
Is it possible to make incremental training?

**Comment by zhongkaifu** [comment]
Currently, RNNSharp doesn't support incremental training, but this is a easy feature to be added. I will implement it very soon.

**Comment by bill3code** [comment]
That's great!
Thank you very much!

**Comment by zhongkaifu** [comment]
This check has already been checked-in. You can try it now.
