### ISSUE TITLE
maybe it's time to support CUDA !

### ISSUE THREAD

**Issue by AvenSun** [zhongkaifu/RNNSharp#36]
Hi,
   RNNSharp is great for .net developers. but sometimes training time is kinda long.
I found one interesting project [managedCuda](https://github.com/kunzmi/managedCuda) which is complete .net wrapper for the CUDA Driver API. so maybe it's a good idea to merge it into rnnsharp.
best regards!
           Adesun

**Comment by zhongkaifu** [comment]
Thanks @Adesun 

I once slightly modified RNNSharp to apply managedCuda, however, its performance is worse than CPU+SIMD version.  :(

To leverage GPU performance completely, RNNSharp has to have a large design and code modification. It's timing cost and currently, I don't have bandwidth for it.

**Comment by AvenSun** [comment]
I see. thx.
