### ISSUE TITLE
Poor performance in Sequential Tagging

### ISSUE THREAD

**Issue by bratao** [zhongkaifu/RNNSharp#4]
Hello !

Thanks again for this awesome project !

From my understanding, the performance for text sequential tagging should be equal or more than CRFSharp or CRF++ right ?
My problem is to semantic tag a big single, continuous text ( hundreds of pages). 

In CRF++ I get a error token ratio of about 0.5%. In RNNSharp I can´t get it better than 40%. a gigantic different. I tried LSTM and BPTT with CRF on or off. No luck.

This is expected for my use case, or am I doing something wrong ?

**Comment by zhongkaifu** [comment]
Hi Bratao,

What's feature set did you use ? I suggest you to use both lexical features and dense features, such as word embedding. Could you please share your configuration file and command line with me ? I can look into it.

For CRFSharp and CRF++, both of them should have similiar performance. In addition, both of them are able to generate huge features according unigram and bigram feature template, the number of feature set can be much larger than what's RNNSharp has.

Did you try your data set by using CRFSharp or CRF++ ?

**Comment by bratao** [comment]
Hi @zhongkaifu ,

Thank you for helping me. My objective is to segment a stream of text. I use B and I tags to identify the beginning and middle of sections that interest me.

For example, imagine that we have a string like this:
> 
Id:01 - Zhang Wei x Joao da Silva
My objective is to extract the Id and persons, so a possible tagging is something like this:


```
Id: (B-id)
01 (I-id)
- (O)
Zhang (B-name) 
Wei (I-name) 
x (O)
Joao (B-name) 
da (I-name) 
Silva(I-name) 

```
I'm using a very simple feature set, just to compare the performance with CRF++. The only feature I use is the token in lower-case.

In CRF++ I get 98% of f1_score. Using RNNSharp,  I get in the best case, 28% of f1_score. Something is clearly wrong.

This is the command line I use:

```
.\Bin\TFeatureBin.exe -mode build -template bruno-template.txt -inputfile bruno-data.txt -ftrfile bruno-features -minfreq 1

.\Bin\RNNSharpConsole.exe -mode train -trainfile bruno-data.txt -modelfile .\bruno-model.bin -validfile bruno-valid.txt -ftrfile .\config_bruno.txt -tagfile .\bruno-tags.txt -modeltype 1 -layersize 200 -alpha 0.1 -crf 1 -maxiter 20 -savestep 200K -dir 0 -dropout 

```


My config is this:
```

#The file name for template feature set
TFEATURE_FILENAME:.\bruno-features
#The context range for template feature set. In below, the context is current token, next token and next after next token
TFEATURE_CONTEXT: 0

#The word embedding data file name generated by Txt2Vec (https://github.com/zhongkaifu/Txt2Vec)
WORDEMBEDDING_FILENAME:.\vector.bin
#The context range for word embedding.
WORDEMBEDDING_CONTEXT: 0
#The column index applied word embedding feature
WORDEMBEDDING_COLUMN: 0
```


And the template is this:


```
U01:%x[0,0]
U02:%x[0,1]
```

Can you spot anything that I'm doing wrong ??

Thank you so much. I miss Seattle and the bike trails !

**Comment by zhongkaifu** [comment]
#1: How did you generate vector.bin for word embedding features ?

#2: I saw you are using U02:%x[0,1] in template. How many columns are you using in your training corpus "bruno-data.txt“ ? Can you share a few lines as example with me ?

#3: I suggest you trying these parameters at first.
.\Bin\RNNSharpConsole.exe -mode train -trainfile bruno-data.txt -modelfile .\bruno-model.bin -validfile bruno-valid.txt -ftrfile .\config_bruno.txt -tagfile .\bruno-tags.txt -modeltype 0 -layersize 200 -alpha 0.1 -crf 0 -maxiter 20 -savestep 200K -dir 1

**Comment by bratao** [comment]
@zhongkaifu ,

#1 - I generated a continuous text from my dataset (this is extracted from PDFs) and feed to Txt2Vec with this command:

> Txt2VecConsole.exe -mode train -trainfile corpus.txt -modelfile vector.bin -debug 1 -vector-size 200 -window 5 -min-count 1 -sample 1e-4 -cbow 1 -threads 1 -save-step 1M -negative 15 -iter 20 

The total corpus was from the input files. It is small, something like 1M of text.

#2 - It is like that:

```
Proc	proc	B-numero_processo
.	.	I-numero_processo
0197531-67.2015.8.19.0001	0197531-67.2015.8.19.0001	I-numero_processo
-	-	O
SEBASTIÃO	sebastião	B-envolvido
GONÇALVES	gonçalves	I-envolvido
LEITE	leite	I-envolvido
(	(	B-advogado
Adv	adv	I-advogado
```

If you want, I can send my complete corpus.

#3 - I still do not converge. It keeps like this:

```
info,11/02/2016 22:43:54 [TRACE] Sentences = 20, time escape = 00:02:06.4899589s, speed = 0,158115317404851
info,11/02/2016 22:43:54 [TRACE] In training: log probability = -37889,3161939014, cross-entropy = 1,02723097357027, perplexity = 2,03810866562367
info,11/02/2016 22:43:54 [TRACE] Start validation ...
info,11/02/2016 22:43:54 [TRACE] In validation: error token ratio = 56,359102244389% error sentence ratio = 100%
info,11/02/2016 22:43:54 [TRACE] In training: log probability = -310,722174807037, cross-entropy = 2,57405666383042, perplexity = 5,95481489963951

``

**Comment by zhongkaifu** [comment]
I think 1M file for word embedding training is not enough. You can try "Txt2VecConsole.exe -mode distance..." to verify the quality of vector.bin

Since word embedding training is totally unsupervised, you can try to use bigger corpus to train it.

**Comment by bratao** [comment]
@zhongkaifu , Oh, thank you for clarifying this. I will try with a bigger corpus !

My understanding was that word embedding was just a extra set of features, and without it , it would compare to CRFSharp.

Thank you again so much for the help !!! I will report if I get any success !
